jaredharbison = User.create(username: "jaredharbison", first_name: "Jared", last_name: "Harbison", email: "jared.harbison@gmail.com", admin: "true", queen: "false", password_digest: "jared1234")
bettermidler = User.create(username: "bettermidler", first_name: "Better", last_name: "Midler", email: "better@midler.com", admin: "true", queen: "true", password_digest: "better1234")
hovabooboo = User.create(username: "hovabooboo", first_name: "Hova", last_name: "Harbison-Ortiz", email: "hova@naughtydog.com", admin: "false", queen: "false", password_digest: "hova1234")
alyssaedwards = User.create(username: "alyssaedwards", first_name: "Alyssa", last_name: "Edwards", email: "alyssa@edwards.com", admin: "false", queen: "true", password_digest: "alyssa1234")
#= User.create(username: "", first_name: "", last_name: "", email: "", admin: "", queen: "", password_digest: "")
